### ISSUE TITLE
articles/testing/running-tests-terminal.md

### ISSUE THREAD

**Issue by rowa97** [stoplightio/docs#105] opened 2018-01-24 22:08 UTC

**Comment by pytlesk4** [comment] 2018-02-06 21:03
Update article: https://help.stoplight.io/scenarios/conducting-scenarios-outside-of-stoplight/running-scenarios

**Comment by rossmcdonald** [comment] 2018-02-16 22:26
Dupe of https://github.com/stoplightio/docs/issues/140

**Closed by rossmcdonald** 2018-02-16 22:26 UTC
